import logging


def log_exception(e):
    logging.error(e)
